# Generated by Django 4.2.16 on 2025-11-08 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'db_table': 'actor_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='AgeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Age',
                'verbose_name_plural': 'Ages',
                'db_table': 'age_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ArtistOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'artist_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='AspectRatioOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aspect Ratio',
                'verbose_name_plural': 'Aspect Ratios',
                'db_table': 'aspect_ratio_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CameraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'db_table': 'camera_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CameraTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Type',
                'verbose_name_plural': 'Camera Types',
                'db_table': 'camera_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CinematographerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Cinematographer',
                'verbose_name_plural': 'Cinematographers',
                'db_table': 'cinematographer_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ColoristOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colorist',
                'verbose_name_plural': 'Colorists',
                'db_table': 'colorist_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hex_code', models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'color_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CompositionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Composition',
                'verbose_name_plural': 'Compositions',
                'db_table': 'composition_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CostumeDesignerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costume Designer',
                'verbose_name_plural': 'Costume Designers',
                'db_table': 'costume_designer_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='DescriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Description',
                'verbose_name_plural': 'Descriptions',
                'db_table': 'description_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='DirectorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'db_table': 'director_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='EditorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editors',
                'db_table': 'editor_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='EthnicityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ethnicity',
                'verbose_name_plural': 'Ethnicities',
                'db_table': 'ethnicity_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FilmingLocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filming Location',
                'verbose_name_plural': 'Filming Locations',
                'db_table': 'filming_location_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FilmStockOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film Stock',
                'verbose_name_plural': 'Film Stocks',
                'db_table': 'film_stock_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FormatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
                'db_table': 'format_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FrameRateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frame Rate',
                'verbose_name_plural': 'Frame Rates',
                'db_table': 'frame_rate_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FrameSizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frame Size',
                'verbose_name_plural': 'Frame Sizes',
                'db_table': 'frame_size_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='GenderOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
                'db_table': 'gender_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='GenreOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('release_year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('dominant_colors', models.JSONField(blank=True, null=True)),
                ('primary_color_hex', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('primary_colors', models.JSONField(blank=True, null=True)),
                ('secondary_color_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('color_palette', models.JSONField(blank=True, null=True)),
                ('color_samples', models.JSONField(blank=True, null=True)),
                ('color_histogram', models.JSONField(blank=True, null=True)),
                ('color_search_terms', models.JSONField(blank=True, null=True)),
                ('color_temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('hue_range', models.CharField(blank=True, max_length=20, null=True)),
                ('prompt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('exclude_nudity', models.BooleanField(default=False)),
                ('exclude_violence', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteriorExteriorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interior/Exterior',
                'verbose_name_plural': 'Interior/Exterior',
                'db_table': 'interior_exterior_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LabProcessOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Process',
                'verbose_name_plural': 'Lab Processes',
                'db_table': 'lab_process_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens',
                'verbose_name_plural': 'Lenses',
                'db_table': 'lens_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LensSizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Size',
                'verbose_name_plural': 'Lens Sizes',
                'db_table': 'lens_size_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LensTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Type',
                'verbose_name_plural': 'Lens Types',
                'db_table': 'lens_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LightingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lighting',
                'verbose_name_plural': 'Lighting',
                'db_table': 'lighting_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LightingTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lighting Type',
                'verbose_name_plural': 'Lighting Types',
                'db_table': 'lighting_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'location_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LocationTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
                'db_table': 'location_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='MediaTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Media Type',
                'verbose_name_plural': 'Media Types',
                'db_table': 'media_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('year', models.IntegerField(blank=True, db_index=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('genre', models.CharField(blank=True, max_length=500, null=True)),
                ('colorist', models.CharField(blank=True, max_length=500, null=True)),
                ('production_designer', models.CharField(blank=True, max_length=500, null=True)),
                ('costume_designer', models.CharField(blank=True, max_length=500, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('language', models.CharField(blank=True, max_length=200, null=True)),
                ('image_count', models.IntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MovieOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='NumberOfPeopleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Number of People',
                'verbose_name_plural': 'Number of People',
                'db_table': 'number_of_people_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='OpticalFormatOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Optical Format',
                'verbose_name_plural': 'Optical Formats',
                'db_table': 'optical_format_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDesignerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Designer',
                'verbose_name_plural': 'Production Designers',
                'db_table': 'production_designer_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resolution',
                'verbose_name_plural': 'Resolutions',
                'db_table': 'resolution_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='SettingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'setting_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ShadeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shade',
                'verbose_name_plural': 'Shades',
                'db_table': 'shade_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ShotTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shot Time',
                'verbose_name_plural': 'Shot Times',
                'db_table': 'shot_time_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ShotTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shot Type',
                'verbose_name_plural': 'Shot Types',
                'db_table': 'shot_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('usage_count', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeOfDayOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time of Day',
                'verbose_name_plural': 'Time of Day',
                'db_table': 'time_of_day_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='TimePeriodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Period',
                'verbose_name_plural': 'Time Periods',
                'db_table': 'time_period_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='VfxBackingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VFX Backing',
                'verbose_name_plural': 'VFX Backings',
                'db_table': 'vfx_backing_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='YearOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='Option value')),
                ('display_order', models.IntegerField(blank=True, help_text='Display order', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'db_table': 'year_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='yearoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_year_value'),
        ),
        migrations.AddConstraint(
            model_name='vfxbackingoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_vfx_backing_value'),
        ),
        migrations.AddConstraint(
            model_name='timeperiodoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_time_period_value'),
        ),
        migrations.AddConstraint(
            model_name='timeofdayoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_time_of_day_value'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tag_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-usage_count'], name='tag_usage_idx'),
        ),
        migrations.AddConstraint(
            model_name='shottypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_shot_type_value'),
        ),
        migrations.AddConstraint(
            model_name='shottimeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_shot_time_value'),
        ),
        migrations.AddConstraint(
            model_name='shadeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_shade_value'),
        ),
        migrations.AddConstraint(
            model_name='settingoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_setting_value'),
        ),
        migrations.AddConstraint(
            model_name='resolutionoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_resolution_value'),
        ),
        migrations.AddConstraint(
            model_name='productiondesigneroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_production_designer_value'),
        ),
        migrations.AddConstraint(
            model_name='opticalformatoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_optical_format_value'),
        ),
        migrations.AddConstraint(
            model_name='numberofpeopleoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_number_of_people_value'),
        ),
        migrations.AddIndex(
            model_name='movieoption',
            index=models.Index(fields=['slug'], name='movie_opt_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='movieoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_movie_value'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cinematographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_cinematographer', to='images.cinematographeroption'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_director', to='images.directoroption'),
        ),
        migrations.AddField(
            model_name='movie',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_editor', to='images.editoroption'),
        ),
        migrations.AddConstraint(
            model_name='mediatypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_media_type_value'),
        ),
        migrations.AddConstraint(
            model_name='locationtypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_location_type_value'),
        ),
        migrations.AddConstraint(
            model_name='locationoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_location_value'),
        ),
        migrations.AddConstraint(
            model_name='lightingtypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lighting_type_value'),
        ),
        migrations.AddConstraint(
            model_name='lightingoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lighting_value'),
        ),
        migrations.AddConstraint(
            model_name='lenstypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lens_type_value'),
        ),
        migrations.AddConstraint(
            model_name='lenssizeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lens_size_value'),
        ),
        migrations.AddConstraint(
            model_name='lensoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lens_value'),
        ),
        migrations.AddConstraint(
            model_name='labprocessoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lab_process_value'),
        ),
        migrations.AddConstraint(
            model_name='interiorexterioroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_interior_exterior_value'),
        ),
        migrations.AddField(
            model_name='image',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.actoroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.ageoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.artistoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='aspect_ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.aspectratiooption'),
        ),
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.cameraoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='camera_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.cameratypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='cinematographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.cinematographeroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.coloroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='colorist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.coloristoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.compositionoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='costume_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.costumedesigneroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='description_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.descriptionoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.directoroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.editoroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.ethnicityoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='film_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.filmstockoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='filming_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.filminglocationoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.formatoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='frame_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.framerateoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='frame_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.framesizeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.genderoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.genreoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='interior_exterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.interiorexterioroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lab_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.labprocessoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lensoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lens_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lenssizeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lens_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lenstypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lightingoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lighting_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lightingtypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.locationoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.locationtypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.mediatypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.movie'),
        ),
        migrations.AddField(
            model_name='image',
            name='number_of_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.numberofpeopleoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='optical_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.opticalformatoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='production_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.productiondesigneroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.resolutionoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.settingoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.shadeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='shot_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.shottimeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='shot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.shottypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.tag'),
        ),
        migrations.AddField(
            model_name='image',
            name='time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.timeofdayoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.timeperiodoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='vfx_backing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.vfxbackingoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.yearoption'),
        ),
        migrations.AddConstraint(
            model_name='genreoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_genre_value'),
        ),
        migrations.AddConstraint(
            model_name='genderoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_gender_value'),
        ),
        migrations.AddConstraint(
            model_name='framesizeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_frame_size_value'),
        ),
        migrations.AddConstraint(
            model_name='framerateoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_frame_rate_value'),
        ),
        migrations.AddConstraint(
            model_name='formatoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_format_value'),
        ),
        migrations.AddConstraint(
            model_name='filmstockoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_film_stock_value'),
        ),
        migrations.AddConstraint(
            model_name='filminglocationoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_filming_location_value'),
        ),
        migrations.AddConstraint(
            model_name='ethnicityoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_ethnicity_value'),
        ),
        migrations.AddIndex(
            model_name='editoroption',
            index=models.Index(fields=['slug'], name='editor_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='editoroption',
            index=models.Index(fields=['value'], name='editor_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='editoroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_editor_value'),
        ),
        migrations.AddIndex(
            model_name='directoroption',
            index=models.Index(fields=['slug'], name='director_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='directoroption',
            index=models.Index(fields=['value'], name='director_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='directoroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_director_value'),
        ),
        migrations.AddConstraint(
            model_name='descriptionoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_description_value'),
        ),
        migrations.AddConstraint(
            model_name='costumedesigneroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_costume_designer_value'),
        ),
        migrations.AddConstraint(
            model_name='compositionoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_composition_value'),
        ),
        migrations.AddConstraint(
            model_name='coloroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_color_value'),
        ),
        migrations.AddConstraint(
            model_name='coloristoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_colorist_value'),
        ),
        migrations.AddIndex(
            model_name='cinematographeroption',
            index=models.Index(fields=['slug'], name='cinematographer_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='cinematographeroption',
            index=models.Index(fields=['value'], name='cinematographer_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='cinematographeroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_cinematographer_value'),
        ),
        migrations.AddConstraint(
            model_name='cameratypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_camera_type_value'),
        ),
        migrations.AddConstraint(
            model_name='cameraoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_camera_value'),
        ),
        migrations.AddConstraint(
            model_name='aspectratiooption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_aspect_ratio_value'),
        ),
        migrations.AddIndex(
            model_name='artistoption',
            index=models.Index(fields=['slug'], name='artist_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='artistoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_artist_value'),
        ),
        migrations.AddConstraint(
            model_name='ageoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_age_value'),
        ),
        migrations.AddIndex(
            model_name='actoroption',
            index=models.Index(fields=['slug'], name='actor_slug_idx'),
        ),
        migrations.AddConstraint(
            model_name='actoroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_actor_value'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'year'], name='movie_title_year_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-image_count'], name='movie_img_count_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='image_created_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['movie', 'created_at'], name='image_movie_created'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['shot_type', 'lighting'], name='image_shot_lighting'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['color', 'lighting'], name='image_color_lighting'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['primary_color_hex'], name='image_primary_color'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_active', 'created_at'], name='image_active_created'),
        ),
    ]
