# Generated by Django 4.2.24 on 2025-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_slug_movie_slug_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Cast members (comma-separated)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cinematographer',
            field=models.CharField(blank=True, help_text='Director of Photography', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='colorist',
            field=models.CharField(blank=True, help_text='Color grading artist', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='costume_designer',
            field=models.CharField(blank=True, help_text='Costume designer', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, help_text='Country of production', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, help_text='Movie description/synopsis'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='Movie director', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Movie duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='editor',
            field=models.CharField(blank=True, help_text='Film editor', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, help_text='Movie genre (e.g., Drama, Action, Comedy)', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, help_text='Original language', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_designer',
            field=models.CharField(blank=True, help_text='Production designer', max_length=255),
        ),
    ]
