# Generated by Django 4.2.24 on 2025-09-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_movie_cast_movie_cinematographer_movie_colorist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_palette',
            field=models.JSONField(blank=True, help_text='Complete color palette extracted from image', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='dominant_colors',
            field=models.JSONField(blank=True, help_text='List of dominant colors with hex codes and percentages', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='primary_color_hex',
            field=models.CharField(blank=True, help_text='Primary color hex code (e.g., #FF5733)', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='secondary_color_hex',
            field=models.CharField(blank=True, help_text='Secondary color hex code', max_length=7, null=True),
        ),
    ]
