# Generated by Django 4.2.24 on 2025-09-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_add_color_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_histogram',
            field=models.JSONField(blank=True, help_text='Color histogram data', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='color_samples',
            field=models.JSONField(blank=True, help_text='10 color samples from different parts of the image', null=True),
        ),
    ]
