# Generated by Django 4.2.24 on 2025-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_add_color_samples_and_histogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_search_terms',
            field=models.JSONField(blank=True, help_text='Search-friendly color terms for easy matching', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='primary_colors',
            field=models.JSONField(blank=True, help_text='List of top 5 primary colors with hex codes, percentages, and metadata', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='primary_color_hex',
            field=models.CharField(blank=True, help_text='Main primary color hex code (e.g., #FF5733)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='secondary_color_hex',
            field=models.CharField(blank=True, help_text='Secondary color hex code (for backward compatibility)', max_length=7, null=True),
        ),
    ]
