# Generated by Django 5.2.6 on 2025-09-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_add_multiple_primary_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_temperature',
            field=models.CharField(blank=True, help_text='Color temperature (warm, cool, neutral)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='hue_range',
            field=models.CharField(blank=True, help_text='Hue range for color matching (e.g., 0-60)', max_length=20, null=True),
        ),
    ]
