# Generated by Django 4.2.24 on 2025-09-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_add_color_temperature_hue_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='شناسه منحصربه\u200cفرد فیلتر', max_length=100, unique=True)),
                ('name', models.CharField(help_text='نام نمایشی فیلتر', max_length=100)),
                ('filter_type', models.CharField(help_text='نوع فیلتر (text, multi_select, color_picker)', max_length=50)),
                ('format_description', models.TextField(blank=True, help_text='توضیح فرمت استفاده از فیلتر')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش فیلتر')),
                ('is_active', models.BooleanField(default=True, help_text='آیا فیلتر فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='مقدار گزینه', max_length=100)),
                ('label', models.CharField(help_text='برچسب نمایشی گزینه', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='ترتیب نمایش گزینه')),
                ('is_active', models.BooleanField(default=True, help_text='آیا گزینه فعال است')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter', models.ForeignKey(help_text='فیلتر مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='images.filter')),
            ],
            options={
                'verbose_name': 'Filter Option',
                'verbose_name_plural': 'Filter Options',
                'ordering': ['filter', 'display_order', 'label'],
                'unique_together': {('filter', 'value')},
            },
        ),
    ]
