# Generated by Django 5.2.6 on 2025-09-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_add_per_filter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ageoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='aspectratiooption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='cameratypeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='coloroption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='compositionoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='ethnicityoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='formatoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='framerateoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='framesizeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='genderoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='genreoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='interiorexterioroption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='lenssizeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='lenstypeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='lightingoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='lightingtypeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='mediatypeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='numberofpeopleoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='opticalformatoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='resolutionoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='shottypeoption',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='timeofdayoption',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='image',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.ageoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='aspect_ratio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.aspectratiooption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='camera_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.cameratypeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.coloroption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.compositionoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.ethnicityoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.formatoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='frame_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.framerateoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='frame_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.framesizeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.genderoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.genreoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='interior_exterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.interiorexterioroption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lens_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lenssizeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lens_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lenstypeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lighting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lightingoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='lighting_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lightingtypeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.mediatypeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='number_of_people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.numberofpeopleoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='optical_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.opticalformatoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.resolutionoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='shot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.shottypeoption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='time_of_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.timeofdayoption'),
        ),
    ]
