# Generated by Django 5.2.6 on 2025-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_update_image_model_foreign_keys'),
    ]

    operations = [
        # Add indexes for better performance
        migrations.AlterField(
            model_name='ageoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='aspectratiooption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='cameratypeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='coloroption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='compositionoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='ethnicityoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='formatoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='framerateoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='framesizeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='genderoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='genreoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='interiorexterioroption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='lenssizeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='lenstypeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='lightingoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='lightingtypeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='mediatypeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='numberofpeopleoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='opticalformatoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='resolutionoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='shottypeoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),
        migrations.AlterField(
            model_name='timeofdayoption',
            name='value',
            field=models.TextField(help_text='مقدار گزینه'),
        ),

        # Add database indexes for value fields (SQLite compatible)
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_genre_value ON genre_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_genre_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_color_value ON color_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_color_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_media_type_value ON media_type_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_media_type_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_aspect_ratio_value ON aspect_ratio_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_aspect_ratio_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_optical_format_value ON optical_format_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_optical_format_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_format_value ON format_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_format_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_interior_exterior_value ON interior_exterior_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_interior_exterior_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_time_of_day_value ON time_of_day_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_time_of_day_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_number_of_people_value ON number_of_people_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_number_of_people_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_gender_value ON gender_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_gender_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_age_value ON age_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_age_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_ethnicity_value ON ethnicity_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_ethnicity_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_frame_size_value ON frame_size_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_frame_size_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_shot_type_value ON shot_type_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_shot_type_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_composition_value ON composition_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_composition_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_lens_size_value ON lens_size_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_lens_size_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_lens_type_value ON lens_type_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_lens_type_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_lighting_value ON lighting_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_lighting_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_lighting_type_value ON lighting_type_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_lighting_type_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_camera_type_value ON camera_type_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_camera_type_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_resolution_value ON resolution_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_resolution_value;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_frame_rate_value ON frame_rate_options (value);",
            reverse_sql="DROP INDEX IF EXISTS idx_frame_rate_value;"
        ),

        # Add indexes for display_order
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_genre_display_order ON genre_options (display_order);",
            reverse_sql="DROP INDEX IF EXISTS idx_genre_display_order;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_color_display_order ON color_options (display_order);",
            reverse_sql="DROP INDEX IF EXISTS idx_color_display_order;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_media_type_display_order ON media_type_options (display_order);",
            reverse_sql="DROP INDEX IF EXISTS idx_media_type_display_order;"
        ),
    ]
