# Generated by Django 5.2.6 on 2025-09-17 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_remove_old_filter_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabProcessOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab Process Option',
                'verbose_name_plural': 'Lab Process Options',
                'db_table': 'lab_process_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_lab_process_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='lab_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.labprocessoption'),
        ),
        migrations.CreateModel(
            name='TimePeriodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Period Option',
                'verbose_name_plural': 'Time Period Options',
                'db_table': 'time_period_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_time_period_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.timeperiodoption'),
        ),
    ]
