# Generated by Django 4.2.24 on 2025-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_add_new_option_models_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movie Option',
                'verbose_name_plural': 'Movie Options',
                'db_table': 'movie_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='movieoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_movie_value'),
        ),
    ]
