# Generated by Django 4.2.24 on 2025-09-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_movieoption_movieoption_uq_movie_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieoption',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug for the movie', max_length=255, unique=True),
        ),
    ]
