# Generated by Django 4.2.24 on 2025-09-21 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_movieoption_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actor Option',
                'verbose_name_plural': 'Actor Options',
                'db_table': 'actor_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='CameraOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Camera Option',
                'verbose_name_plural': 'Camera Options',
                'db_table': 'camera_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='DescriptionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Description Option',
                'verbose_name_plural': 'Description Options',
                'db_table': 'description_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FilmingLocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filming Location Option',
                'verbose_name_plural': 'Filming Location Options',
                'db_table': 'filming_location_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='FilmStockOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Film Stock Option',
                'verbose_name_plural': 'Film Stock Options',
                'db_table': 'film_stock_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LensOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lens Option',
                'verbose_name_plural': 'Lens Options',
                'db_table': 'lens_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Option',
                'verbose_name_plural': 'Location Options',
                'db_table': 'location_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='LocationTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Type Option',
                'verbose_name_plural': 'Location Type Options',
                'db_table': 'location_type_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='SettingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting Option',
                'verbose_name_plural': 'Setting Options',
                'db_table': 'setting_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='ShotTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shot Time Option',
                'verbose_name_plural': 'Shot Time Options',
                'db_table': 'shot_time_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='VfxBackingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VFX Backing Option',
                'verbose_name_plural': 'VFX Backing Options',
                'db_table': 'vfx_backing_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='vfxbackingoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_vfx_backing_value'),
        ),
        migrations.AddConstraint(
            model_name='shottimeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_shot_time_value'),
        ),
        migrations.AddConstraint(
            model_name='settingoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_setting_value'),
        ),
        migrations.AddConstraint(
            model_name='locationtypeoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_location_type_value'),
        ),
        migrations.AddConstraint(
            model_name='locationoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_location_value'),
        ),
        migrations.AddConstraint(
            model_name='lensoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_lens_value'),
        ),
        migrations.AddConstraint(
            model_name='filmstockoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_film_stock_value'),
        ),
        migrations.AddConstraint(
            model_name='filminglocationoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_filming_location_value'),
        ),
        migrations.AddConstraint(
            model_name='descriptionoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_description_value'),
        ),
        migrations.AddConstraint(
            model_name='cameraoption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_camera_value'),
        ),
        migrations.AddConstraint(
            model_name='actoroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_actor_value'),
        ),
        migrations.AddField(
            model_name='image',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.actoroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.cameraoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='description_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.descriptionoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='film_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.filmstockoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='filming_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.filminglocationoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='lens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.lensoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.locationoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.locationtypeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.settingoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='shot_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.shottimeoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='vfx_backing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.vfxbackingoption'),
        ),
    ]
