# Generated by Django 4.2.24 on 2025-09-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_actoroption_cameraoption_descriptionoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filming_location',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location_type',
        ),
        migrations.DeleteModel(
            name='FilmingLocationOption',
        ),
        migrations.DeleteModel(
            name='LocationTypeOption',
        ),
    ]
