# Generated by Django 4.2.24 on 2025-09-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_remove_image_filming_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actoroption',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly slug for the actor', max_length=255, unique=True),
        ),
    ]
