# Generated by Django 4.2.24 on 2025-09-24 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_actoroption_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinematographerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug for the cinematographer', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Cinematographer Option',
                'verbose_name_plural': 'Cinematographer Options',
                'db_table': 'cinematographer_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='DirectorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug for the director', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Director Option',
                'verbose_name_plural': 'Director Options',
                'db_table': 'director_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.CreateModel(
            name='EditorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug for the editor', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Editor Option',
                'verbose_name_plural': 'Editor Options',
                'db_table': 'editor_options',
                'ordering': ['display_order', 'value'],
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='genre',
        ),
        migrations.AddConstraint(
            model_name='editoroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_editor_value'),
        ),
        migrations.AddConstraint(
            model_name='directoroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_director_value'),
        ),
        migrations.AddConstraint(
            model_name='cinematographeroption',
            constraint=models.UniqueConstraint(fields=('value',), name='uq_cinematographer_value'),
        ),
        migrations.AddField(
            model_name='image',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.genreoption'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cinematographer',
            field=models.ForeignKey(blank=True, help_text='Director of Photography', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_cinematographer', to='images.cinematographeroption'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, help_text='Movie director', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_director', to='images.directoroption'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='editor',
            field=models.ForeignKey(blank=True, help_text='Film editor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_editor', to='images.editoroption'),
        ),
    ]
