# Generated by Django 4.2.24 on 2025-09-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_cinematographeroption_directoroption_editoroption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='colorist',
            field=models.CharField(blank=True, help_text='Color grading artist', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='costume_designer',
            field=models.CharField(blank=True, help_text='Costume designer', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, help_text='Country of production', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, help_text='Movie genre (e.g., Drama, Action, Comedy)', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, help_text='Original language', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_designer',
            field=models.CharField(blank=True, help_text='Production designer', max_length=500),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
