# Generated by Django 4.2.24 on 2025-09-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_alter_movie_colorist_alter_movie_costume_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, help_text='Cast members (comma-separated)', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, help_text='Movie description/synopsis', null=True),
        ),
    ]
