# Generated by Django 4.2.24 on 2025-09-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_alter_movie_cast_alter_movie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='colorist',
            field=models.CharField(blank=True, help_text='Color grading artist', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='costume_designer',
            field=models.CharField(blank=True, help_text='Costume designer', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_designer',
            field=models.CharField(blank=True, help_text='Production designer', max_length=500, null=True),
        ),
    ]
