# Generated by Django 4.2.24 on 2025-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_alter_movie_colorist_alter_movie_costume_designer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, help_text='Country of production', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, help_text='Original language', max_length=200, null=True),
        ),
    ]
