# Generated by Django 4.2.24 on 2025-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_alter_movie_country_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, help_text='Movie genre (e.g., Drama, Action, Comedy)', max_length=500, null=True),
        ),
    ]
