# Generated by Django 5.2.6 on 2025-10-04 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cinematographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.cinematographeroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.directoroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.editoroption'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='image_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['movie'], name='image_movie_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['release_year'], name='image_release_year_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['media_type'], name='image_media_type_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['color'], name='image_color_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['shot_type'], name='image_shot_type_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lighting'], name='image_lighting_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['camera_type'], name='image_camera_type_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['time_of_day'], name='image_time_of_day_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['interior_exterior'], name='image_interior_exterior_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['gender'], name='image_gender_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['age'], name='image_age_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['ethnicity'], name='image_ethnicity_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['frame_size'], name='image_frame_size_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['aspect_ratio'], name='image_aspect_ratio_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['optical_format'], name='image_optical_format_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['format'], name='image_format_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lab_process'], name='image_lab_process_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['time_period'], name='image_time_period_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['number_of_people'], name='image_number_of_people_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['composition'], name='image_composition_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lens_size'], name='image_lens_size_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lens_type'], name='image_lens_type_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lighting_type'], name='image_lighting_type_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['resolution'], name='image_resolution_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['frame_rate'], name='image_frame_rate_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['actor'], name='image_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['camera'], name='image_camera_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lens'], name='image_lens_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['location'], name='image_location_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['setting'], name='image_setting_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['film_stock'], name='image_film_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['shot_time'], name='image_shot_time_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['description_filter'], name='image_description_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['vfx_backing'], name='image_vfx_backing_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['director'], name='image_director_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['cinematographer'], name='image_cinematographer_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['editor'], name='image_editor_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['movie', 'created_at'], name='image_movie_created_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['release_year', 'created_at'], name='image_year_created_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['shot_type', 'lighting'], name='image_shot_lighting_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['color', 'lighting'], name='image_color_lighting_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['camera_type', 'lens_type'], name='image_camera_lens_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['shot_type', 'time_of_day'], name='image_shot_time_of_day_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['lighting', 'interior_exterior'], name='image_lighting_location_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['camera_type', 'film_stock'], name='image_camera_film_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['actor', 'movie'], name='image_actor_movie_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['location', 'setting'], name='image_location_setting_idx'),
        ),
    ]
