# Generated by Django 5.2.6 on 2025-10-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0026_add_crew_filters_to_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColoristOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Colorist Option',
                'verbose_name_plural': 'Colorist Options',
                'db_table': 'colorist_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_colorist_value')],
            },
        ),
        migrations.CreateModel(
            name='CostumeDesignerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Costume Designer Option',
                'verbose_name_plural': 'Costume Designer Options',
                'db_table': 'costume_designer_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_costume_designer_value')],
            },
        ),
        migrations.CreateModel(
            name='ProductionDesignerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Designer Option',
                'verbose_name_plural': 'Production Designer Options',
                'db_table': 'production_designer_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_production_designer_value')],
            },
        ),
    ]
