# Generated by Django 5.2.6 on 2025-10-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0027_coloristoption_costumedesigneroption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug for the artist', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Artist Option',
                'verbose_name_plural': 'Artist Options',
                'db_table': 'artist_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_artist_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.artistoption'),
        ),
        migrations.CreateModel(
            name='FilmingLocationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filming Location Option',
                'verbose_name_plural': 'Filming Location Options',
                'db_table': 'filming_location_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_filming_location_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='filming_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.filminglocationoption'),
        ),
        migrations.CreateModel(
            name='LocationTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location Type Option',
                'verbose_name_plural': 'Location Type Options',
                'db_table': 'location_type_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_location_type_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='location_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.locationtypeoption'),
        ),
        migrations.CreateModel(
            name='ShadeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shade Option',
                'verbose_name_plural': 'Shade Options',
                'db_table': 'shade_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_shade_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='shade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.shadeoption'),
        ),
        migrations.CreateModel(
            name='YearOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(help_text='مقدار گزینه')),
                ('display_order', models.IntegerField(blank=True, help_text='ترتیب نمایش', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='متادیتای اضافی', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Year Option',
                'verbose_name_plural': 'Year Options',
                'db_table': 'year_options',
                'ordering': ['display_order', 'value'],
                'constraints': [models.UniqueConstraint(fields=('value',), name='uq_year_value')],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.yearoption'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['shade'], name='image_shade_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['artist'], name='image_artist_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['filming_location'], name='image_filming_location_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['location_type'], name='image_location_type_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['year'], name='image_year_filter_idx'),
        ),
    ]
