# Generated by Django 5.2.6 on 2025-10-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_artistoption_image_artist_filminglocationoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='colorist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.coloristoption'),
        ),
        migrations.AddField(
            model_name='image',
            name='costume_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.costumedesigneroption'),
        ),
        migrations.AddField(
            model_name='image',
            name='production_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='images.productiondesigneroption'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['colorist'], name='image_colorist_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['costume_designer'], name='image_costume_designer_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['production_designer'], name='image_production_designer_idx'),
        ),
    ]
