# Generated by Django 4.2.25 on 2025-10-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_image_colorist_image_costume_designer_and_more'),
    ]

    operations = [
    ]
