# Generated by Django 4.2.16 on 2025-11-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0030_add_ultra_fast_indexes'),
    ]

    operations = [
    ]
