# Generated by Django 4.2.16 on 2025-11-03 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0031_add_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='image',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.movie'),
        ),
    ]
