# Generated by Django 5.2.7 on 2025-11-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0032_remove_image_id_image_is_active_image_prompt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actoroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
        migrations.AlterModelOptions(
            name='ageoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Age', 'verbose_name_plural': 'Ages'},
        ),
        migrations.AlterModelOptions(
            name='artistoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='aspectratiooption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Aspect Ratio', 'verbose_name_plural': 'Aspect Ratios'},
        ),
        migrations.AlterModelOptions(
            name='cameraoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
        migrations.AlterModelOptions(
            name='cameratypeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Camera Type', 'verbose_name_plural': 'Camera Types'},
        ),
        migrations.AlterModelOptions(
            name='cinematographeroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Cinematographer', 'verbose_name_plural': 'Cinematographers'},
        ),
        migrations.AlterModelOptions(
            name='coloristoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Colorist', 'verbose_name_plural': 'Colorists'},
        ),
        migrations.AlterModelOptions(
            name='coloroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='compositionoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Composition', 'verbose_name_plural': 'Compositions'},
        ),
        migrations.AlterModelOptions(
            name='costumedesigneroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Costume Designer', 'verbose_name_plural': 'Costume Designers'},
        ),
        migrations.AlterModelOptions(
            name='descriptionoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Description', 'verbose_name_plural': 'Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='directoroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='editoroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Editor', 'verbose_name_plural': 'Editors'},
        ),
        migrations.AlterModelOptions(
            name='ethnicityoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Ethnicity', 'verbose_name_plural': 'Ethnicities'},
        ),
        migrations.AlterModelOptions(
            name='filminglocationoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Filming Location', 'verbose_name_plural': 'Filming Locations'},
        ),
        migrations.AlterModelOptions(
            name='filmstockoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Film Stock', 'verbose_name_plural': 'Film Stocks'},
        ),
        migrations.AlterModelOptions(
            name='formatoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Format', 'verbose_name_plural': 'Formats'},
        ),
        migrations.AlterModelOptions(
            name='framerateoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Frame Rate', 'verbose_name_plural': 'Frame Rates'},
        ),
        migrations.AlterModelOptions(
            name='framesizeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Frame Size', 'verbose_name_plural': 'Frame Sizes'},
        ),
        migrations.AlterModelOptions(
            name='genderoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Gender', 'verbose_name_plural': 'Genders'},
        ),
        migrations.AlterModelOptions(
            name='genreoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='interiorexterioroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Interior/Exterior', 'verbose_name_plural': 'Interior/Exterior'},
        ),
        migrations.AlterModelOptions(
            name='labprocessoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Lab Process', 'verbose_name_plural': 'Lab Processes'},
        ),
        migrations.AlterModelOptions(
            name='lensoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Lens', 'verbose_name_plural': 'Lenses'},
        ),
        migrations.AlterModelOptions(
            name='lenssizeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Lens Size', 'verbose_name_plural': 'Lens Sizes'},
        ),
        migrations.AlterModelOptions(
            name='lenstypeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Lens Type', 'verbose_name_plural': 'Lens Types'},
        ),
        migrations.AlterModelOptions(
            name='lightingoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Lighting', 'verbose_name_plural': 'Lighting'},
        ),
        migrations.AlterModelOptions(
            name='lightingtypeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Lighting Type', 'verbose_name_plural': 'Lighting Types'},
        ),
        migrations.AlterModelOptions(
            name='locationoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='locationtypeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Location Type', 'verbose_name_plural': 'Location Types'},
        ),
        migrations.AlterModelOptions(
            name='mediatypeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Media Type', 'verbose_name_plural': 'Media Types'},
        ),
        migrations.AlterModelOptions(
            name='movieoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='numberofpeopleoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Number of People', 'verbose_name_plural': 'Number of People'},
        ),
        migrations.AlterModelOptions(
            name='opticalformatoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Optical Format', 'verbose_name_plural': 'Optical Formats'},
        ),
        migrations.AlterModelOptions(
            name='productiondesigneroption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Production Designer', 'verbose_name_plural': 'Production Designers'},
        ),
        migrations.AlterModelOptions(
            name='resolutionoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Resolution', 'verbose_name_plural': 'Resolutions'},
        ),
        migrations.AlterModelOptions(
            name='settingoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterModelOptions(
            name='shadeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Shade', 'verbose_name_plural': 'Shades'},
        ),
        migrations.AlterModelOptions(
            name='shottimeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Shot Time', 'verbose_name_plural': 'Shot Times'},
        ),
        migrations.AlterModelOptions(
            name='shottypeoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Shot Type', 'verbose_name_plural': 'Shot Types'},
        ),
        migrations.AlterModelOptions(
            name='timeofdayoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Time of Day', 'verbose_name_plural': 'Time of Day'},
        ),
        migrations.AlterModelOptions(
            name='timeperiodoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Time Period', 'verbose_name_plural': 'Time Periods'},
        ),
        migrations.AlterModelOptions(
            name='vfxbackingoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'VFX Backing', 'verbose_name_plural': 'VFX Backings'},
        ),
        migrations.AlterModelOptions(
            name='yearoption',
            options={'ordering': ['display_order', 'value'], 'verbose_name': 'Year', 'verbose_name_plural': 'Years'},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_movie_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_release_year_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_media_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_color_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_shot_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lighting_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_camera_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_time_of_day_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_interior_exterior_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_gender_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_age_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_ethnicity_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_frame_size_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_aspect_ratio_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_optical_format_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_format_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lab_process_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_time_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_number_of_people_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_composition_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lens_size_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lens_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lighting_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_resolution_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_frame_rate_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_actor_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_camera_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lens_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_setting_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_film_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_shot_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_description_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_vfx_backing_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_director_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_cinematographer_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_editor_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_year_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_camera_lens_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_shot_time_of_day_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_lighting_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_camera_film_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_actor_movie_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_location_setting_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_shade_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_artist_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_filming_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_location_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_year_filter_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_colorist_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_costume_designer_idx',
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='image_production_designer_idx',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='image_created_idx',
            old_name='image_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='image_movie_created',
            old_name='image_movie_created_idx',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='image_shot_lighting',
            old_name='image_shot_lighting_idx',
        ),
        migrations.RenameIndex(
            model_name='image',
            new_name='image_color_lighting',
            old_name='image_color_lighting_idx',
        ),
        migrations.AddField(
            model_name='coloroption',
            name='hex_code',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='usage_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='actoroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='actoroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='actoroption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='actoroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='ageoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='ageoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='ageoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='artistoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='artistoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='artistoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='artistoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='aspectratiooption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='aspectratiooption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='aspectratiooption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='cameraoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='cameraoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='cameraoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='cameratypeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='cameratypeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='cameratypeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='cinematographeroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='cinematographeroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='cinematographeroption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cinematographeroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='coloristoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='coloristoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='coloristoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='coloroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='coloroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='coloroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='compositionoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='compositionoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='compositionoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='costumedesigneroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='costumedesigneroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='costumedesigneroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='descriptionoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='descriptionoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='descriptionoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='directoroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='directoroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='directoroption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='directoroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='editoroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='editoroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='editoroption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='editoroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='ethnicityoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='ethnicityoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='ethnicityoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='filminglocationoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='filminglocationoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='filminglocationoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='filmstockoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='filmstockoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='filmstockoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='formatoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='formatoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='formatoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='framerateoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='framerateoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='framerateoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='framesizeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='framesizeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='framesizeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='genderoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='genderoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='genderoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='genreoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='genreoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='genreoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='image',
            name='color_histogram',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='color_palette',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='color_samples',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='color_search_terms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='color_temperature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='dominant_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='hue_range',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.movie'),
        ),
        migrations.AlterField(
            model_name='image',
            name='primary_color_hex',
            field=models.CharField(blank=True, db_index=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='primary_colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='release_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='secondary_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interiorexterioroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='interiorexterioroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='interiorexterioroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='labprocessoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='labprocessoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='labprocessoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='lensoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='lensoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='lensoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='lenssizeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='lenssizeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='lenssizeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='lenstypeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='lenstypeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='lenstypeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='lightingoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='lightingoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='lightingoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='lightingtypeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='lightingtypeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='lightingtypeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='locationoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='locationoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='locationoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='locationtypeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='locationtypeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='locationtypeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='mediatypeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='mediatypeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='mediatypeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cinematographer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_cinematographer', to='images.cinematographeroption'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='colorist',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='costume_designer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_director', to='images.directoroption'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_as_editor', to='images.editoroption'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_count',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production_designer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='movieoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='movieoption',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='movieoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='numberofpeopleoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='numberofpeopleoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='numberofpeopleoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='opticalformatoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='opticalformatoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='opticalformatoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='productiondesigneroption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='productiondesigneroption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='productiondesigneroption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='resolutionoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='resolutionoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='resolutionoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='settingoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='settingoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='settingoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='shadeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='shadeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='shadeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='shottimeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='shottimeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='shottimeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='shottypeoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='shottypeoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='shottypeoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='timeofdayoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='timeofdayoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='timeofdayoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='timeperiodoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='timeperiodoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='timeperiodoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='vfxbackingoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='vfxbackingoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='vfxbackingoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AlterField(
            model_name='yearoption',
            name='display_order',
            field=models.IntegerField(blank=True, help_text='Display order', null=True),
        ),
        migrations.AlterField(
            model_name='yearoption',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional metadata', null=True),
        ),
        migrations.AlterField(
            model_name='yearoption',
            name='value',
            field=models.TextField(help_text='Option value'),
        ),
        migrations.AddIndex(
            model_name='actoroption',
            index=models.Index(fields=['slug'], name='actor_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='artistoption',
            index=models.Index(fields=['slug'], name='artist_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='cinematographeroption',
            index=models.Index(fields=['slug'], name='cinematographer_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='cinematographeroption',
            index=models.Index(fields=['value'], name='cinematographer_value_idx'),
        ),
        migrations.AddIndex(
            model_name='directoroption',
            index=models.Index(fields=['slug'], name='director_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='directoroption',
            index=models.Index(fields=['value'], name='director_value_idx'),
        ),
        migrations.AddIndex(
            model_name='editoroption',
            index=models.Index(fields=['slug'], name='editor_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='editoroption',
            index=models.Index(fields=['value'], name='editor_value_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['primary_color_hex'], name='image_primary_color'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_active', 'created_at'], name='image_active_created'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'year'], name='movie_title_year_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-image_count'], name='movie_img_count_idx'),
        ),
        migrations.AddIndex(
            model_name='movieoption',
            index=models.Index(fields=['slug'], name='movie_opt_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='tag_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['-usage_count'], name='tag_usage_idx'),
        ),
    ]
