# Generated by Django 4.2.16 on 2025-11-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0033_alter_actoroption_options_alter_ageoption_options_and_more'),
    ]

    operations = [
    ]
