# Generated by Django 4.2.16 on 2025-11-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0034_auto_20251103_1222'),
    ]

    operations = [
    ]
