# Generated by Django 4.2.16 on 2025-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0035_auto_20251103_1227'),
    ]

    operations = [
    ]
