# Generated by Django 4.2.16 on 2025-11-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0036_auto_20251103_1229'),
    ]

    operations = [
    ]
