# Generated by Django 4.2.16 on 2025-11-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_squashed_0037_auto_20251103_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uuid',
            new_name='id',
        ),
    ]
