# Generated by Django 4.2.24 on 2025-09-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('format', models.TextField(verbose_name='Format')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Filter',
                'verbose_name_plural': 'Filters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MovieFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.filter')),
            ],
            options={
                'db_table': 'moviefilter',
            },
            bases=('common.filter',),
        ),
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.filter')),
            ],
            options={
                'db_table': 'searchfilter',
            },
            bases=('common.filter',),
        ),
        migrations.CreateModel(
            name='ShadeFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.filter')),
            ],
            options={
                'db_table': 'shadefilter',
            },
            bases=('common.filter',),
        ),
        migrations.CreateModel(
            name='TagsFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.filter')),
            ],
            options={
                'db_table': 'tagsfilter',
            },
            bases=('common.filter',),
        ),
        migrations.CreateModel(
            name='TimePeriodFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_period_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_time_period_options',
            },
        ),
        migrations.CreateModel(
            name='TimeOfDayFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_of_day_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_time_of_day_options',
            },
        ),
        migrations.CreateModel(
            name='SubjectEthnicityFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_ethnicity_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_subject_ethnicity_options',
            },
        ),
        migrations.CreateModel(
            name='SubjectAgeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_age_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_subject_age_options',
            },
        ),
        migrations.CreateModel(
            name='ShotTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_type_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_shot_type_options',
            },
        ),
        migrations.CreateModel(
            name='OpticalFormatFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optical_format_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_optical_format_options',
            },
        ),
        migrations.CreateModel(
            name='NumPeopleFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_people_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_numpeople_options',
            },
        ),
        migrations.CreateModel(
            name='MediaTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_type_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_media_type_options',
            },
        ),
        migrations.CreateModel(
            name='LightingTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_type_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_lighting_type_options',
            },
        ),
        migrations.CreateModel(
            name='LightingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lighting_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_lighting_options',
            },
        ),
        migrations.CreateModel(
            name='LensTypeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lens_type_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_lens_type_options',
            },
        ),
        migrations.CreateModel(
            name='LabProcessFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_process_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_lab_process_options',
            },
        ),
        migrations.CreateModel(
            name='IntExtFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='int_ext_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_int_ext_options',
            },
        ),
        migrations.CreateModel(
            name='GenreFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_genre_options',
            },
        ),
        migrations.CreateModel(
            name='GenderFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_gender_options',
            },
        ),
        migrations.CreateModel(
            name='FrameSizeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_size_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_frame_size_options',
            },
        ),
        migrations.CreateModel(
            name='FormatFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='format_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_format_options',
            },
        ),
        migrations.CreateModel(
            name='CompositionFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_composition_options',
            },
        ),
        migrations.CreateModel(
            name='ColorFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_color_options',
            },
        ),
        migrations.CreateModel(
            name='AspectRatioFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspect_ratio_options', to='common.filter', verbose_name='Filter')),
            ],
            options={
                'db_table': 'filter_aspect_ratio_options',
            },
        ),
    ]
