# Generated by Django 5.2.6 on 2025-09-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspectratiofilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='colorfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='compositionfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='formatfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='framesizefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='genderfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='genrefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='intextfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='labprocessfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='lenstypefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='lightingfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='lightingtypefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='mediatypefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='numpeoplefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='opticalformatfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='shottypefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='subjectagefilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='subjectethnicityfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='timeofdayfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterModelOptions(
            name='timeperiodfilter',
            options={'ordering': ['value'], 'verbose_name': 'Filter Option', 'verbose_name_plural': 'Filter Options'},
        ),
        migrations.AlterUniqueTogether(
            name='aspectratiofilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='colorfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='compositionfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='formatfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='framesizefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='genderfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='genrefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='intextfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='labprocessfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='lenstypefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='lightingfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='lightingtypefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='mediatypefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='numpeoplefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='opticalformatfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='shottypefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectagefilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectethnicityfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='timeofdayfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='timeperiodfilter',
            unique_together={('filter', 'value')},
        ),
        migrations.AddIndex(
            model_name='aspectratiofilter',
            index=models.Index(fields=['value'], name='filter_aspe_value_5fb9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='aspectratiofilter',
            index=models.Index(fields=['slug'], name='filter_aspe_slug_1af90b_idx'),
        ),
        migrations.AddIndex(
            model_name='colorfilter',
            index=models.Index(fields=['value'], name='filter_colo_value_f0fef0_idx'),
        ),
        migrations.AddIndex(
            model_name='colorfilter',
            index=models.Index(fields=['slug'], name='filter_colo_slug_fc019d_idx'),
        ),
        migrations.AddIndex(
            model_name='compositionfilter',
            index=models.Index(fields=['value'], name='filter_comp_value_20f385_idx'),
        ),
        migrations.AddIndex(
            model_name='compositionfilter',
            index=models.Index(fields=['slug'], name='filter_comp_slug_d796d5_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['name'], name='common_filt_name_7ecf28_idx'),
        ),
        migrations.AddIndex(
            model_name='filter',
            index=models.Index(fields=['type'], name='common_filt_type_6713bf_idx'),
        ),
        migrations.AddIndex(
            model_name='formatfilter',
            index=models.Index(fields=['value'], name='filter_form_value_af54df_idx'),
        ),
        migrations.AddIndex(
            model_name='formatfilter',
            index=models.Index(fields=['slug'], name='filter_form_slug_64fa97_idx'),
        ),
        migrations.AddIndex(
            model_name='framesizefilter',
            index=models.Index(fields=['value'], name='filter_fram_value_71f901_idx'),
        ),
        migrations.AddIndex(
            model_name='framesizefilter',
            index=models.Index(fields=['slug'], name='filter_fram_slug_c49dd6_idx'),
        ),
        migrations.AddIndex(
            model_name='genderfilter',
            index=models.Index(fields=['value'], name='filter_gend_value_883265_idx'),
        ),
        migrations.AddIndex(
            model_name='genderfilter',
            index=models.Index(fields=['slug'], name='filter_gend_slug_b94fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='genrefilter',
            index=models.Index(fields=['value'], name='filter_genr_value_6dd877_idx'),
        ),
        migrations.AddIndex(
            model_name='genrefilter',
            index=models.Index(fields=['slug'], name='filter_genr_slug_24ba9b_idx'),
        ),
        migrations.AddIndex(
            model_name='intextfilter',
            index=models.Index(fields=['value'], name='filter_int__value_fd6d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='intextfilter',
            index=models.Index(fields=['slug'], name='filter_int__slug_242d11_idx'),
        ),
        migrations.AddIndex(
            model_name='labprocessfilter',
            index=models.Index(fields=['value'], name='filter_lab__value_e079d3_idx'),
        ),
        migrations.AddIndex(
            model_name='labprocessfilter',
            index=models.Index(fields=['slug'], name='filter_lab__slug_83bd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='lenstypefilter',
            index=models.Index(fields=['value'], name='filter_lens_value_015aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='lenstypefilter',
            index=models.Index(fields=['slug'], name='filter_lens_slug_6b3d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='lightingfilter',
            index=models.Index(fields=['value'], name='filter_ligh_value_bfe655_idx'),
        ),
        migrations.AddIndex(
            model_name='lightingfilter',
            index=models.Index(fields=['slug'], name='filter_ligh_slug_6dc466_idx'),
        ),
        migrations.AddIndex(
            model_name='lightingtypefilter',
            index=models.Index(fields=['value'], name='filter_ligh_value_caadc4_idx'),
        ),
        migrations.AddIndex(
            model_name='lightingtypefilter',
            index=models.Index(fields=['slug'], name='filter_ligh_slug_76ca55_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatypefilter',
            index=models.Index(fields=['value'], name='filter_medi_value_d4874c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediatypefilter',
            index=models.Index(fields=['slug'], name='filter_medi_slug_6f4c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='numpeoplefilter',
            index=models.Index(fields=['value'], name='filter_nump_value_3127bb_idx'),
        ),
        migrations.AddIndex(
            model_name='numpeoplefilter',
            index=models.Index(fields=['slug'], name='filter_nump_slug_9967a5_idx'),
        ),
        migrations.AddIndex(
            model_name='opticalformatfilter',
            index=models.Index(fields=['value'], name='filter_opti_value_2220d8_idx'),
        ),
        migrations.AddIndex(
            model_name='opticalformatfilter',
            index=models.Index(fields=['slug'], name='filter_opti_slug_cb6e30_idx'),
        ),
        migrations.AddIndex(
            model_name='shottypefilter',
            index=models.Index(fields=['value'], name='filter_shot_value_b932eb_idx'),
        ),
        migrations.AddIndex(
            model_name='shottypefilter',
            index=models.Index(fields=['slug'], name='filter_shot_slug_dab9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectagefilter',
            index=models.Index(fields=['value'], name='filter_subj_value_991f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectagefilter',
            index=models.Index(fields=['slug'], name='filter_subj_slug_3b300d_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectethnicityfilter',
            index=models.Index(fields=['value'], name='filter_subj_value_63598a_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectethnicityfilter',
            index=models.Index(fields=['slug'], name='filter_subj_slug_ca3d70_idx'),
        ),
        migrations.AddIndex(
            model_name='timeofdayfilter',
            index=models.Index(fields=['value'], name='filter_time_value_3fb2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeofdayfilter',
            index=models.Index(fields=['slug'], name='filter_time_slug_5b589b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeperiodfilter',
            index=models.Index(fields=['value'], name='filter_time_value_c49a80_idx'),
        ),
        migrations.AddIndex(
            model_name='timeperiodfilter',
            index=models.Index(fields=['slug'], name='filter_time_slug_d103b4_idx'),
        ),
    ]
