# Generated by Django 4.2.23 on 2025-09-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='image_ids',
            new_name='image_slugs',
        ),
    ]
